### ISSUE TITLE
Fira Code iScript not Present

### ISSUE THREAD

**Issue by argctl** [Ugotsta/notebook-ui#1]
The font Fira Code iScript that the theme relies on isn't present. I disabled the fonts package I'm using and manually put in the font name mentioned in editor settings and it doesn't work. Any ideas?

**Comment by R3V1Z3** [comment]
I should have been clearer about the font. The font is totally free, it just needs to be installed.

To simplify things a little, I've just pushed an update that links to the font files on a CDN. If you update to the latest version, it should at least render as long as you have an internet connection.

It's best to install the font though. Here's the repository:
https://github.com/kencrocken/FiraCodeiScript

You can simply download the .ttf font files individually or use `git clone https://github.com/kencrocken/FiraCodeiScript` to download the full directory locally.

From there, you can install them by whatever means your OS uses. On Windows and Linux, you should be able to right-click the .ttf files and select 'Install'. I think the same might work on Mac.

Or you can just copy the .ttf files directly into your system's font folder (which varies).

I'll try to sort out a more elegant solution meanwhile. Any feedback is welcome. :)

**Comment by argctl** [comment]
I sent a pull request with a fix. I left the fonts package as a submodule so that still needs to be tested with apm. The git submodule can be removed and the files added in the same spot with the same directory name and it will work if the submodule makes apm not work correctly.

**Comment by R3V1Z3** [comment]
Sounds good, I've merged it, added the font files and added a link to you as a contributor in the README.
